from django.shortcuts import render, redirect
from .models import Topic
from .forms import TopicForm, EntryForm

# Create your views here.


def index(request):
    """The home page for learning_logs."""
    return render(request, 'learning_logs/index.html')


def topics(request):
    """Page to display all available topics."""
    topics = Topic.objects.order_by('date_added')
    context = {'topics': topics}
    return render(request, 'learning_logs/topics.html', context)


def topic(request, topic_id):
    """Page to display one specific topic and its entries."""
    topic = Topic.objects.get(id=topic_id)
    entries = topic.entry_set.order_by('-date_added')
    context = {'topic': topic, 'entries': entries}
    return render(request, 'learning_logs/topic.html', context)


def new_topic(request):
    """Page to create a new topic.
    The new_topic() function needs to handle two different situations: initial
    requests for the new_topic page (in which case it should show a blank form)
    and the processing of any data submitted in the form."""
    if request.method != "POST":
        # No data submitted, create blank form.
        form = TopicForm()
    else:
        # POST data was submitted, process the data into a form.
        form = TopicForm(data=request.POST)
        if form.is_valid():
            form.save()
            # When new topic is saved, redirect to a page generated by the
            # 'topics' view in 'views.py'.
            return redirect("learning_logs:topics")

    # Display a blank or invalid form.
    context = {"form": form}
    return render(request, "learning_logs/new_topic.html", context)


def new_entry(request, topic_id):
    """Page to add a new entry for a specific topic."""
    topic = Topic.objects.get(id=topic_id)

    if request.method == 'POST':
        form = EntryForm(data=request.POST)
        if form.is_valid():
            new_entry = form.save()
            new_entry.topic = topic
            new_entry.save()
            # Redirect to the same topic's page generated by the 'topic' view
            # in 'views.py'.
            return redirect("learning_logs:topic", topic_id=topic_id)
            # Notice how we pass it the 'topic_id' variable, as it is needed
            # in 'views.py' to show the appropriate topic page.

    # If form is empty or invalid, create a new blank EntryForm...
    else:
        form = EntryForm()

    # Give the template for a new blank form the context variables and let it
    # display the blank form to the user.
    context = {'topic': topic, 'form': form}
    return render(request, "learning_logs/new_entry.html", context)
